name: Deploy Frontend to Firebase Hosting

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'dist/frontend/**'
      - 'firebase.json'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npx nx build frontend --prod

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          # Use the new secret containing the JSON key
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}'
          projectId: ${{ secrets.GCP_PROJECT_ID }}
          channelId: live
          entryPoint: ./
