name: Deploy API to Google Cloud Functions

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build API for production
        # Removed --with-dependencies as it is not supported by webpack-cli and causes build to fail.
        run: npx nx run api:build --prod

      - name: Copy deployment files
        run: |
          # Copy the built main.js and package.json to the dist/api directory for deployment.
          cp api/package.json dist/api/package.json

      - name: Deploy API to Cloud Functions
        # The gcloud command now runs on its own without any extra flags.
        run: >
          gcloud functions deploy nfl-pick-em-api
          --gen2
          --region=us-east1
          --source=./dist/api
          --entry-point=startServer
          --runtime=nodejs20
          --trigger-http
          --allow-unauthenticated
