name: Deploy Frontend to Firebase Hosting

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'frontend/**'
      - 'dist/frontend/**'
      - 'firebase.json'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: |
          if [ "$GITHUB_REF" = "refs/heads/main" ]; then
            npx nx build frontend --configuration=production
          else
            npx nx build frontend --configuration=staging
          fi

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: ${{ github.ref == 'refs/heads/main' && secrets.FIREBASE_SERVICE_ACCOUNT_KEY_PROD || secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          projectId: ${{ github.ref == 'refs/heads/main' && 'nfl-pick-em-prod' || secrets.GCP_PROJECT_ID }}
          channelId: live
          entryPoint: ./
