name: Deploy API to Google Cloud Run

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'api/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ github.ref == 'refs/heads/main' && secrets.GCP_SA_KEY_PROD || secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ github.ref == 'refs/heads/main' && 'nfl-pick-em-prod' || secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for Google Artifact Registry
        run: |
          gcloud auth configure-docker us-east1-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build -t ${{ github.ref == 'refs/heads/main' && 'us-east1-docker.pkg.dev/nfl-pick-em-prod/api-repo/api:latest' || 'us-east1-docker.pkg.dev/nfl-pick--em-dev/api-repo/api:latest' }} .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push ${{ github.ref == 'refs/heads/main' && 'us-east1-docker.pkg.dev/nfl-pick-em-prod/api-repo/api:latest' || 'us-east1-docker.pkg.dev/nfl-pick--em-dev/api-repo/api:latest' }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy nfl-pick-em-api \
            --image=${{ github.ref == 'refs/heads/main' && 'us-east1-docker.pkg.dev/nfl-pick-em-prod/api-repo/api:latest' || 'us-east1-docker.pkg.dev/nfl-pick--em-dev/api-repo/api:latest' }} \
            --platform=managed \
            --region=us-east1 \
            --allow-unauthenticated \
            --port=8080
